// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2_vYvw3krg7J-G-PaHAP3p7aSFJAGFpc',
    appId: '1:225402657868:web:8c57ff83fb71bdba2268e9',
    messagingSenderId: '225402657868',
    projectId: 'fir-app-7fb76',
    authDomain: 'fir-app-7fb76.firebaseapp.com',
    storageBucket: 'fir-app-7fb76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL-RDHey3RgMyLLyJu41_i8Iy5aR_HmNE',
    appId: '1:225402657868:android:aa4bc026c54f57482268e9',
    messagingSenderId: '225402657868',
    projectId: 'fir-app-7fb76',
    storageBucket: 'fir-app-7fb76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGWYxmC845R84H7uSLVctgpW59sSfgEW0',
    appId: '1:225402657868:ios:6cc462266d445aab2268e9',
    messagingSenderId: '225402657868',
    projectId: 'fir-app-7fb76',
    storageBucket: 'fir-app-7fb76.firebasestorage.app',
    iosBundleId: 'com.example.sampleflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGWYxmC845R84H7uSLVctgpW59sSfgEW0',
    appId: '1:225402657868:ios:6cc462266d445aab2268e9',
    messagingSenderId: '225402657868',
    projectId: 'fir-app-7fb76',
    storageBucket: 'fir-app-7fb76.firebasestorage.app',
    iosBundleId: 'com.example.sampleflutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2_vYvw3krg7J-G-PaHAP3p7aSFJAGFpc',
    appId: '1:225402657868:web:75178353def13dc72268e9',
    messagingSenderId: '225402657868',
    projectId: 'fir-app-7fb76',
    authDomain: 'fir-app-7fb76.firebaseapp.com',
    storageBucket: 'fir-app-7fb76.firebasestorage.app',
  );
}
